### ISSUE TITLE
Unsupported Hardware MH_ERROR_ALREADY_CREATED

### ISSUE THREAD

**Issue by Demion** [zeffy/wufuc#146]
I keep getting Unsupported Hardware from time to time, `MH_ERROR_ALREADY_CREATED` error.
Usually complete reboot helps, manual Windows Update service (wuauserv) restart does not seem to help.
Clean original install, no antivirus software, Windows Defender / UAC disabled completely.

wufuc v1.0.0.191
Windows 8.1 x64 Professional (Version 6.3.9600)
Intel Pentium G4560 CPU.
```
03/22/18 14:43:15 [rundll32.exe:1416] wufuc_inject(96): [INFO] Successfully injected into process! (ProcessId=392)
03/22/18 14:43:15 [svchost.exe:392] cb_start(110): [INFO] Hooked RegQueryValueExW! (Module=KernelBase.dll, Address=00007FFFBD7A4090)
03/22/18 14:43:15 [svchost.exe:392] cb_start(137): [INFO] Hooked LoadLibraryExW! (Module=KernelBase.dll, Address=00007FFFBD7A8D10)
03/22/18 14:43:26 [svchost.exe:392] wufuc_hook(158): [INFO] Supported Windows Update Agent version: 7.9.9600.18838
03/22/18 14:43:26 [svchost.exe:392] wufuc_hook(178): [INFO] Matched IsDeviceServiceable function! (Offset=1C4DEC, Address=00007FFFA9F54DEC)
03/22/18 14:43:26 [svchost.exe:392] wufuc_hook(184): [INFO] Hooked IsDeviceServiceable! (Address=00007FFFA9F54DEC)
03/22/18 21:02:48 [svchost.exe:392] wufuc_hook(158): [INFO] Supported Windows Update Agent version: 7.9.9600.18838
03/22/18 21:02:48 [svchost.exe:392] wufuc_hook(178): [INFO] Matched IsDeviceServiceable function! (Offset=1C4DEC, Address=00007FFFA2714DEC)
03/22/18 21:02:48 [svchost.exe:392] wufuc_hook(184): [INFO] Hooked IsDeviceServiceable! (Address=00007FFFA2714DEC)
03/23/18 08:47:46 [svchost.exe:392] wufuc_hook(158): [INFO] Supported Windows Update Agent version: 7.9.9600.18838
03/23/18 08:47:46 [svchost.exe:392] wufuc_hook(178): [INFO] Matched IsDeviceServiceable function! (Offset=1C4DEC, Address=00007FFFA1F94DEC)
03/23/18 08:47:46 [svchost.exe:392] wufuc_hook(184): [INFO] Hooked IsDeviceServiceable! (Address=00007FFFA1F94DEC)
03/23/18 13:43:50 [svchost.exe:392] wufuc_hook(158): [INFO] Supported Windows Update Agent version: 7.9.9600.18838
03/23/18 13:43:50 [svchost.exe:392] wufuc_hook(178): [INFO] Matched IsDeviceServiceable function! (Offset=1C4DEC, Address=00007FFF96CB4DEC)
03/23/18 13:43:50 [svchost.exe:392] wufuc_hook(184): [INFO] Hooked IsDeviceServiceable! (Address=00007FFF96CB4DEC)
03/23/18 19:00:30 [svchost.exe:392] wufuc_hook(158): [INFO] Supported Windows Update Agent version: 7.9.9600.18838
03/23/18 19:00:30 [svchost.exe:392] wufuc_hook(178): [INFO] Matched IsDeviceServiceable function! (Offset=1C4DEC, Address=00007FFF96CB4DEC)
03/23/18 19:00:30 [svchost.exe:392] wufuc_hook(186): [ERROR] Failed to create IsDeviceServiceable hook! (Status=MH_ERROR_ALREADY_CREATED)
03/23/18 19:13:54 [svchost.exe:392] wufuc_hook(158): [INFO] Supported Windows Update Agent version: 7.9.9600.18838
03/23/18 19:13:54 [svchost.exe:392] wufuc_hook(178): [INFO] Matched IsDeviceServiceable function! (Offset=1C4DEC, Address=00007FFF96CB4DEC)
03/23/18 19:13:54 [svchost.exe:392] wufuc_hook(186): [ERROR] Failed to create IsDeviceServiceable hook! (Status=MH_ERROR_ALREADY_CREATED)
03/23/18 19:20:35 [svchost.exe:392] wufuc_hook(158): [INFO] Supported Windows Update Agent version: 7.9.9600.18838
03/23/18 19:20:35 [svchost.exe:392] wufuc_hook(178): [INFO] Matched IsDeviceServiceable function! (Offset=1C4DEC, Address=00007FFF96CB4DEC)
03/23/18 19:20:35 [svchost.exe:392] wufuc_hook(186): [ERROR] Failed to create IsDeviceServiceable hook! (Status=MH_ERROR_ALREADY_CREATED)
03/23/18 19:21:17 [svchost.exe:392] cb_start(151): [INFO] Unload condition has been met.
03/23/18 19:21:17 [svchost.exe:392] cb_start(162): [INFO] Unloading wufuc and exiting thread.
03/23/18 19:23:22 [rundll32.exe:1416] wufuc_inject(96): [INFO] Successfully injected into process! (ProcessId=376)
03/23/18 19:23:22 [svchost.exe:376] cb_start(110): [INFO] Hooked RegQueryValueExW! (Module=KernelBase.dll, Address=00007FFE7B804090)
03/23/18 19:23:22 [svchost.exe:376] cb_start(137): [INFO] Hooked LoadLibraryExW! (Module=KernelBase.dll, Address=00007FFE7B808D10)
03/23/18 19:23:33 [svchost.exe:376] wufuc_hook(158): [INFO] Supported Windows Update Agent version: 7.9.9600.18838
03/23/18 19:23:33 [svchost.exe:376] wufuc_hook(178): [INFO] Matched IsDeviceServiceable function! (Offset=1C4DEC, Address=00007FFE67764DEC)
03/23/18 19:23:33 [svchost.exe:376] wufuc_hook(184): [INFO] Hooked IsDeviceServiceable! (Address=00007FFE67764DEC)
```
Update: maybe problem is hook is restored, but minhook fail to hook because address is the same (`00007FFF96CB4DEC`) and already in its `g_hooks` list (`MH_ERROR_ALREADY_CREATED`). Sorry if irrelevant.

I guess running Windows update in its own process (`sc config wuauserv type=own`) might be workaround. Will report back. Thanks for your work.

By the way no new updates were installed for all log period. Was working fine till Unsuported Hardware message at 03/23/18 19:00:30. Restarted wuauserv at 03/23/18 19:13:54 and 03/23/18 19:20:35 (did not help). Rebooted PC at 03/23/18 19:23:22.

**Comment by zeffy** [comment]
>Update: maybe problem is hook is restored, but minhook fail to hook because address is the same (00007FFF96CB4DEC) and already in its g_hooks list (MH_ERROR_ALREADY_CREATED). Sorry if irrelevant.

Most likely correct. It's kind of hard to get the hooking of that function right, since `wuaueng.dll` may be loaded and freed multiple times over the life of the `svchost.exe` process, each time removing my hook. I might have to delve into minhook's source to figure out what's going on (or I could just be doing something wrong on my end?). I'll try to get on this when I can. 

In the meantime setting Windows update to run in its own process should indeed work around this issue while I figure out what is causing it.

**Comment by Demion** [comment]
With Windows update in its own process, svchost.exe seems to restart from time to time, but wufuc deduces it as crash and stops working after 3 times threshold. 
Any way to disable this? I have no vs2017 installed cant build right now.

```
03/23/18 19:45:21 [rundll32.exe:1404] wufuc_inject(96): [INFO] Successfully injected into process! (ProcessId=540)
03/23/18 19:45:21 [svchost.exe:540] cb_start(110): [INFO] Hooked RegQueryValueExW! (Module=KernelBase.dll, Address=00007FFD49A74090)
03/23/18 19:45:21 [svchost.exe:540] cb_start(137): [INFO] Hooked LoadLibraryExW! (Module=KernelBase.dll, Address=00007FFD49A78D10)
03/23/18 19:45:32 [svchost.exe:540] wufuc_hook(158): [INFO] Supported Windows Update Agent version: 7.9.9600.18838
03/23/18 19:45:32 [svchost.exe:540] wufuc_hook(178): [INFO] Matched IsDeviceServiceable function! (Offset=1C4DEC, Address=00007FFD32F34DEC)
03/23/18 19:45:32 [svchost.exe:540] wufuc_hook(184): [INFO] Hooked IsDeviceServiceable! (Address=00007FFD32F34DEC)
03/23/18 20:11:13 [svchost.exe:540] wufuc_hook(158): [INFO] Supported Windows Update Agent version: 7.9.9600.18838
03/23/18 20:11:13 [svchost.exe:540] wufuc_hook(178): [INFO] Matched IsDeviceServiceable function! (Offset=1C4DEC, Address=00007FFD2D1E4DEC)
03/23/18 20:11:13 [svchost.exe:540] wufuc_hook(184): [INFO] Hooked IsDeviceServiceable! (Address=00007FFD2D1E4DEC)
03/23/18 20:18:13 [rundll32.exe:1404] wufuc_inject(96): [INFO] Successfully injected into process! (ProcessId=9752)
03/23/18 20:18:13 [svchost.exe:9752] cb_start(137): [INFO] Hooked LoadLibraryExW! (Module=KernelBase.dll, Address=00007FFD49A78D10)
03/23/18 20:18:13 [svchost.exe:9752] wufuc_hook(158): [INFO] Supported Windows Update Agent version: 7.9.9600.18838
03/23/18 20:18:13 [svchost.exe:9752] wufuc_hook(178): [INFO] Matched IsDeviceServiceable function! (Offset=1C4DEC, Address=00007FFD32F34DEC)
03/23/18 20:18:13 [svchost.exe:9752] wufuc_hook(184): [INFO] Hooked IsDeviceServiceable! (Address=00007FFD32F34DEC)
03/23/18 20:19:50 [rundll32.exe:1404] RUNDLL32_StartW(105): [WARNING] A process wufuc injected into has crashed 1 time! (ProcessId=9752)
03/23/18 20:20:02 [rundll32.exe:1404] wufuc_inject(96): [INFO] Successfully injected into process! (ProcessId=8536)
03/23/18 20:20:02 [svchost.exe:8536] cb_start(137): [INFO] Hooked LoadLibraryExW! (Module=KernelBase.dll, Address=00007FFD49A78D10)
03/23/18 20:20:02 [svchost.exe:8536] wufuc_hook(158): [INFO] Supported Windows Update Agent version: 7.9.9600.18838
03/23/18 20:20:02 [svchost.exe:8536] wufuc_hook(178): [INFO] Matched IsDeviceServiceable function! (Offset=1C4DEC, Address=00007FFD186B4DEC)
03/23/18 20:20:02 [svchost.exe:8536] wufuc_hook(184): [INFO] Hooked IsDeviceServiceable! (Address=00007FFD186B4DEC)
03/23/18 20:24:44 [rundll32.exe:1404] RUNDLL32_StartW(105): [WARNING] A process wufuc injected into has crashed 2 times! (ProcessId=8536)
03/23/18 20:24:46 [rundll32.exe:1404] wufuc_inject(96): [INFO] Successfully injected into process! (ProcessId=10328)
03/23/18 20:24:46 [svchost.exe:10328] cb_start(137): [INFO] Hooked LoadLibraryExW! (Module=KernelBase.dll, Address=00007FFD49A78D10)
03/23/18 20:24:46 [svchost.exe:10328] wufuc_hook(158): [INFO] Supported Windows Update Agent version: 7.9.9600.18838
03/23/18 20:24:46 [svchost.exe:10328] wufuc_hook(178): [INFO] Matched IsDeviceServiceable function! (Offset=1C4DEC, Address=00007FFD186B4DEC)
03/23/18 20:24:46 [svchost.exe:10328] wufuc_hook(184): [INFO] Hooked IsDeviceServiceable! (Address=00007FFD186B4DEC)
03/23/18 23:00:39 [rundll32.exe:1404] RUNDLL32_StartW(105): [WARNING] A process wufuc injected into has crashed 3 times! (ProcessId=10328)
03/23/18 23:00:39 [rundll32.exe:1404] RUNDLL32_StartW(108): [ERROR] Crash threshold has been reached, disabling wufuc until next reboot!
03/23/18 23:00:39 [svchost.exe:540] cb_start(151): [INFO] Unload condition has been met.
03/23/18 23:00:39 [svchost.exe:540] cb_start(162): [INFO] Unloading wufuc and exiting thread.
```

**Comment by zeffy** [comment]
That's weird. I never ran into that during my testing. I will look into this further!

As far as disabling that behavior, its not possible at the moment but I can make it optional in the future.

**Comment by Demion** [comment]
> Most likely correct. It's kind of hard to get the hooking of that function right, since wuaueng.dll may be loaded and freed multiple times over the life of the svchost.exe process, each time removing my hook. I might have to delve into minhook's source to figure out what's going on (or I could just be doing something wrong on my end?). I'll try to get on this when I can.

Regarding `MH_ERROR_ALREADY_CREATED` you can try `MH_RemoveHook`. As far as I understand minhook source, `MH_DisableHook` is redundant, cause `MH_RemoveHook` disables hook by itself as well.

Something like this
```
status = MH_CreateHook(pTarget, IsDeviceServiceable_hook, NULL);

if (status == MH_ERROR_ALREADY_CREATED)
{
	MH_RemoveHook(pTarget);

	if (status == MH_OK)
		status = MH_CreateHook(pTarget, IsDeviceServiceable_hook, NULL);
}

if ( status == MH_OK ) {
	status = MH_EnableHook(pTarget);
```
Haven't looked into sources more, not sure if it will succeed removing hook though because of memory already freed. On other hand if address match and its same code in function "header" then it should be fine. 
Does not sound like right solution though, maybe just need to modify minhook source and patch memory (hook) unconditionally.

**Comment by zeffy** [comment]
You may be right. Unfortunately there isn't actually a lot of documentation (examples etc) for MH_RemoveHook as far as I could tell (most of the examples only use MH_DisableHook), so I was trying to be cautious so as not to use it incorrectly. I will play with your idea though. Thank you for all the helpful information!

**Comment by zeffy** [comment]
Thanks, that's helpful information. I haven't had a chance to work on this very much yet. I've been working on a separate project that's been taking up a lot of my time, but I'm almost done with it so I'll be able to put more time into solving this (hopefully) very soon.

Thank you both for your patience and for contributing!

**Comment by zeffy** [comment]
Going to take a stab at this MH_ERROR_ALREADY_CREATED bug today, hopefully I can get it fixed in a clean way.

Just rambling here trying to think of potential solutions:

- Hook FreeLibrary and check the reference count of wuaueng.dll before freeing it, and if it would actually be unloaded upon calling FreeLibrary, remove the IsDeviceServiceable hook before freeing it. I'm not entirely sure if getting the kernel reference count to a library is even possible, and it also seems like this could introduce a race condition (if some code opens another kernel reference to wuaueng.dll in between the time I check the count and when I free it), so doesn't seem like that great of a fix.

- Hook FreeLibrary and just free wuaueng.dll without checking its reference count, but try to get its HMODULE with GetModuleHandle after freeing to see if it it actually unloaded, then remove the Hook unconditionally with code similar to what @Demion proposed up above (MH_RemoveHookEntry).

- Patch Minhook to automatically remove and re-create a hook trampoline that already exists for a function address that has already been register in its g_hooks. Not really sure if I like this solution though.

- maybe some other way? I will edit this as I make progress.

**Comment by Demion** [comment]
`MH_RemoveHookEntry` is not existent minhook API just example how to remove hook entry from minhook `g_hooks` list. 

In my opinion, keeping reference count of load / free library and removing hook before actual DLL unload seems totally redundant, cause this DLL code (memory) will be anyway freed.
Only purpose of removing hook is to remove reference of target function address from minhook `g_hooks` list.

I havent looked at wufuc code in details, but as far as I understand, `MH_CreateHook` is called after pattern of original `IsDeviceServiceable` is detected.

So easily can assume that it is not already hooked (because of original pattern match) and will not be hooked twice, so just remove reference of this function address from `g_hooks` list by code like `MH_RemoveHookEntry` or directly remove check from `MH_CreateHook`.

**Comment by zeffy** [comment]
>MH_RemoveHookEntry is not existent minhook API, just example how to remove hook entry from minhook g_hooks list.

I know, that's what I was trying to say. Sorry if I wasn't clear. :)

>In my opinion, keeping reference count of load / free library and removing hook before actual DLL unload seems totally redundant, cause this DLL code (memory) will be anyway freed.
Only purpose of removing hook is to remove reference of target function address from minhook g_hooks list. 

Agreed, I didn't really like this solution either. Seems messy and error prone.

>I havent looked at wufuc code in details, but as far as I understand, MH_CreateHook is called after pattern of original IsDeviceServiceable is detected.

Correct.

>So easily can assume that it is not already hooked (because of original pattern match, probably because dll is reloaded) and will not be hooked twice, so can just remove reference of this function address from g_hooks list by code like MH_RemoveHookEntry or directly remove check from MH_CreateHook.

Also correct.

>Modifying minhook does not look like clean solution, but might be most "stable" one, because instead of actually unhooking (restoring function "header") before it will be freed anyway, can just remove reference from minhook list, which is not sutuable for this case anyway (dll is loaded and freed multiple times over the life of the process, as you mentioned).

I agree with this as well. 

I had another idea. Prior to the current version (on 0.7 and below), wufuc did not actually hook IsDeviceServiceable, instead it directly patched the BOOL values that the function checked that determined if the CPU check passed or not. In version 1.0 I opted to hook the function instead so that it always returned TRUE, since it made the code much cleaner and easier to understand (directly patching the bytes was ugly and required a lot of pointer arithmetic). 

However, going back to directly patching the values would indeed completely bypass this bug (whether you want to consider it a bug in minhook, or an implementation detail that would technically be my responsibility to handle).

Do you think it would be better if I did that instead of messing with minhook? Curious as to your thoughts.

**Comment by Demion** [comment]
Sorry, I also havent checked previous version source, but patching variable might not work if function is updated, unless this variable address is deduced by some pattern (not fixed offset).
Anyway, I guess, `IsDeviceServiceable` pattern might change as well (probably wont).

Both seem like kinda equvalent solutions. Theoretically patching single variable is even less hassle than hooking - disassembling function "header" length, patching memory, setting trampoline etc (what minhook does, but I believe it is proven to be solid, brilliant tiny library imo).

Just minhook implementation was not taken in consideration case when hook is restored (memory modified / DLL reloaded) and its "foolproof" against hooking twice (`g_hooks` list) is not suitable in this scenario.

Adding extra little function to minhook which will just remove address from dynamic list (`g_hooks`) and free trampoline buffer to provide "rehook" possibility at same target address and not mess with actual DLL memory, seems to me like pretty safe solution as well.

**Comment by zeffy** [comment]
The addresses of the variables to be patched would indeed be deduced from the pattern, I calculate the pointers to the variables based on the instruction operands at certain offsets inside IsDeviceServiceable. So, if the variable patching broke with an update, the pattern used to find the function would also be broken anyway, because the patterns cover these values. For example the pattern for Windows 8.1 x86 is `8BFF 51 833D????????00 7507 A1????????`, the two sets of question marks are pointers to the values I would be patching. Hope that all make sense.

Anyways, I've decided to go this route and just avoid the problem all together, since there really doesn't seem to be a "clean" way to do it with hooking, other than messing with minhook's internals which I'd really like to avoid (I realize it would be simple enough to expose a method that unconditionally removes an entry from g_hooks, but I think doing that is over complicating things when it could be solved some other way). 

> I believe it is proven to be solid, brilliant tiny library imo

Totally agree! I love minhook, and I'm definitely going to keep using it for the other API hooks, because I much prefer it to what I had been using previously (IAT hooking).

**Comment by zeffy** [comment]
This specific issue has been fixed as of a8adfa3, build artifacts are available on appveyor as usual here: https://ci.appveyor.com/project/zeffy/wufuc if you want to test it.

I still haven't fixed the other "false-positive crash detection" bug that you also discovered, though (I created a new issue for it #148), so you'll probably have to change wuauserv back to shared process and reboot.

**Comment by Demion** [comment]
I uninstalled wufuc, rebooted, installed build from a8adfa3 appveyor, rebooted. After that my Windows Update Control Panel explorer was not responding and wuauserv service could not be stopped. 
I killed wuauserv svchost.exe, set it to shared process and rebooted, now seems to work fine.
Not sure if it was one time glitch or something with own process, can not reproduce now.

I will report back in few days (update message).

**Comment by zeffy** [comment]
> After that my Windows Update Control Panel explorer was not responding and wuauserv service could not be stopped (with net stop).

That can happen if you have the WU Control Panel window open when you stop the service, it will become unresponsive. I was testing it under the exact same conditions (Windows 7 x64, wuauserv configured as own process), and the patching procedure seemed to work fine. Let me know if it keeps happening, though.

**Comment by sammilucia** [comment]
I was having the MH_ERROR_ALREADY_CREATED logged also, not immediately - ?possibly after sleep (S1-S4)...

I removed and reinstalled v1.0.0.191-x64 without reboot, ran WU and it worked perfectly until sleep again, then the Windows hardware warning dialog came back and Wufuc logged hook removal was triggered (but no MH_ERROR_ALREADY_CREATED error this time).

Uninstalled v1.0.0.191-x64 and installed v0.7.1.81-x64 and it's now working correctly even after sleep or reboot.

Of note: KB2976978, KB3080149 are not installed.

**Comment by zeffy** [comment]
@sammilucia As noted above the MH_ERROR_ALREADY_CREATED bug has been fixed in the latest appveyor build if you wanted to try it out. Haven't pushed it in an "official" release yet because I'd like to fix a couple other bugs first.

**Comment by sammilucia** [comment]
Thanks @zeffy, I just saw that in your commits after I posted ;p!

I'd go mad without wufuc! Ty 😊
