### ISSUE TITLE
Windows waiting for login...

### ISSUE THREAD

**Issue by cloudtuotuo** [zeffy/wufuc#147]
Before you create an issue, make sure it has not already been reported.

Then, make sure the following things are included in your issue:

- wufuc version (can be viewed in Add & Remove Programs).
  1.0.0.191 x64.msi
- Operating system version and Service Pack (including 32- or 64-bit).
  Windows 7 x64 SP1
- Short description of the issue.
  After boot the PC, before showing login, the system is stopping on ' please waiting '. But the system didn't hang up, because the mouse is still circling.
- Elaborate steps to reproduce the bug/issue being reported.
- Attach wufuc's log file (located at `C:\ProgramData\wufuc\wufuc.log`).
- Any supporting information that could help solve/understand the issue.
  Force rebooting, then entering Safe mode. Rebooting again, the issue disappeared.

Any issues that do not include these, or go more than a week without a
response from the original poster will be subject to closure at my discretion.

If you have questions, be sure to check the FAQ: https://git.io/vASQg

It is common for issues to go unanswered for several days or even weeks,
so please do not take offense at this. 

I read every issue and usually only reply if there is clarification needed,
or if there is a new release pending that will solve the issue.

Thank you for your interest in contributing to this project!

> 3/27/18 15:58:36 [rundll32.exe:7864] wufuc_inject(96): [INFO] Successfully injected into process! (ProcessId=1036)
03/27/18 15:58:36 [svchost.exe:1036] cb_start(110): [INFO] Hooked RegQueryValueExW! (Module=kernel32.dll, Address=0000000077913F00)
03/27/18 15:58:36 [svchost.exe:1036] cb_start(137): [INFO] Hooked LoadLibraryExW! (Module=KernelBase.dll, Address=000007FEFD899AC0)
03/27/18 15:58:36 [svchost.exe:1036] wufuc_hook(158): [INFO] Supported Windows Update Agent version: 7.6.7601.23806
03/27/18 15:58:36 [svchost.exe:1036] wufuc_hook(178): [INFO] Matched IsDeviceServiceable function! (Offset=2F2E4, Address=000007FED9ADF2E4)
03/27/18 15:58:36 [svchost.exe:1036] wufuc_hook(184): [INFO] Hooked IsDeviceServiceable! (Address=000007FED9ADF2E4)
03/28/18 09:36:18 [rundll32.exe:1632] wufuc_inject(96): [INFO] Successfully injected into process! (ProcessId=1032)
03/28/18 09:36:18 [svchost.exe:1032] cb_start(110): [INFO] Hooked RegQueryValueExW! (Module=kernel32.dll, Address=00000000774F3F00)
03/28/18 09:36:18 [svchost.exe:1032] cb_start(137): [INFO] Hooked LoadLibraryExW! (Module=KernelBase.dll, Address=000007FEFD599AC0)
03/28/18 09:38:22 [svchost.exe:1032] wufuc_hook(158): [INFO] Supported Windows Update Agent version: 7.6.7601.23806
03/28/18 09:38:23 [svchost.exe:1032] wufuc_hook(178): [INFO] Matched IsDeviceServiceable function! (Offset=2F2E4, Address=000007FEE765F2E4)
03/28/18 09:38:23 [svchost.exe:1032] wufuc_hook(184): [INFO] Hooked IsDeviceServiceable! (Address=000007FEE765F2E4)
03/29/18 08:34:15 [rundll32.exe:1644] wufuc_inject(96): [INFO] Successfully injected into process! (ProcessId=1052)
03/29/18 08:34:15 [svchost.exe:1052] cb_start(110): [INFO] Hooked RegQueryValueExW! (Module=kernel32.dll, Address=0000000077B53F00)
03/29/18 08:34:15 [svchost.exe:1052] cb_start(137): [INFO] Hooked LoadLibraryExW! (Module=KernelBase.dll, Address=000007FEFDC99AC0)
03/29/18 08:36:30 [svchost.exe:1052] wufuc_hook(158): [INFO] Supported Windows Update Agent version: 7.6.7601.23806
03/29/18 08:36:30 [svchost.exe:1052] wufuc_hook(178): [INFO] Matched IsDeviceServiceable function! (Offset=2F2E4, Address=000007FEF16DF2E4)
03/29/18 08:36:30 [svchost.exe:1052] wufuc_hook(184): [INFO] Hooked IsDeviceServiceable! (Address=000007FEF16DF2E4)
03/30/18 09:22:51 [rundll32.exe:1616] wufuc_inject(96): [INFO] Successfully injected into process! (ProcessId=1036)
03/30/18 09:22:51 [svchost.exe:1036] cb_start(110): [INFO] Hooked RegQueryValueExW! (Module=kernel32.dll, Address=0000000077673F00)
03/30/18 09:22:51 [svchost.exe:1036] cb_start(137): [INFO] Hooked LoadLibraryExW! (Module=KernelBase.dll, Address=000007FEFD619AC0)
03/30/18 09:25:00 [svchost.exe:1036] wufuc_hook(158): [INFO] Supported Windows Update Agent version: 7.6.7601.23806
03/30/18 09:25:01 [svchost.exe:1036] wufuc_hook(178): [INFO] Matched IsDeviceServiceable function! (Offset=2F2E4, Address=000007FEE761F2E4)
03/30/18 09:25:01 [svchost.exe:1036] wufuc_hook(184): [INFO] Hooked IsDeviceServiceable! (Address=000007FEE761F2E4)

**Comment by zeffy** [comment]
There doesn't appear to be anything out of the ordinary in your log. Looks like you've had wufuc installed for about three days according to the log, how many days after you installed wufuc did the it hang on the 'please wait...' message? It's possible this was just a fluke, since like you said the problem went away after you rebooted.

You might be able to find more information about what happened by going to the Windows Event Viewer under the System section and check around the time this occured.

**Comment by koitsu** [comment]
I DO NOT believe this problem is related to wufuc.  Some anecdotal ramblings from me:

I've had this happen on Windows 7 x64 Ultimate (can't speak for other variations) semi-recently, several times in succession.  Hitting Ctrl-Alt-Del during this situation will give indication the machine is shutting down but then does nothing -- indefinitely (I've waited as long as 45 minutes).  You literally have to hit Reset or force power-off (hold power button for several seconds).  It's incredibly difficult to debug given where and when the problem happens.  I've even had it happen on fresh format/reinstalls.  Event Viewer (Windows Logs / System) will contain indications that several core services are timing out after 30 seconds, such as ShellHWDetection, Browser ("Computer Browser"), AeLookupSvc, CertPropSvc, and several others.  Even the Windows Defender service sometimes logs an entry that "it's hung".  It varies, but there always seem to be a "common base set".  This is literally as much information as you can get out of Windows on the matter -- you can't debug it because you can't even log in fully.

Googling around for this type of problem turns up everything under the sun and nothing definitive.  The only thing I found even remotely helpful was a comment on a forum or board somewhere, where a user said that this was an occasional problem for people using "virtual CD/DVD drivers" (Daemon Tools, Alcohol 120%, etc.) -- and in my case, I do in fact have Alcohol 120% installed/am a customer of theirs.  I can't speak for the OP's situation/setup, but at least for me, I've written it off as "some weird thing that's infuriating".

**Comment by cloudtuotuo** [comment]
We deployed this patch in our company. So far, many PC got this issue. And, not all the PC could pass this issue even we did reboot from the safe mode.
We didn't deploy any other software or patches, only this one. So I'm very sure there's something happened related to this patch.

**Comment by cloudtuotuo** [comment]
As zeffy suggested, we checked the logs on the issue PC. There's one error about GPClient. We'll continue digging and update to here.

**Comment by zeffy** [comment]
Well, I can't reproduce this. Just put wufuc on a clean virtual machine and let Windows Update run, it finished, rebooted, and logged back in without issue.

@cloudtuotuo How long had wufuc been installed on PCs that experienced this? Like I said before, your logs had entries dating back 3 days originally - did the issue start happening immediately or was it some time afterwards?

>And, not all the PC could pass this issue even we did reboot from the safe mode.

Could you elaborate on what you mean here? The Task Scheduler (Schedule service) does not run in Safe mode, so neither does wufuc. So if you are still having the problem while in safe mode, then it is very likely something else causing it. Or do you mean it still happens after doing a hard reset -> booting into safe mode -> rebooting again back into normal mode?

**Comment by cloudtuotuo** [comment]
@zeffy After we deployed your patch 3 days later, this issue started happening.
Today, 2 PC got hang on issue. And we tried log in the safe mode (successfully logging in), then reboot. But still hangs at 'Please wait' message. Finally, we chose Last known good configuration, successfully logged in normal mode.

As I mentioned, in the logs, we found the error about GPClient. We googled it, there're many same issue reports related to this error (GPClient issue slow down the login). 
We've changed the GPO according to those suggestions. 
I'll update you tomorrow.

**Comment by kli3ma** [comment]
I confirm this problem. 8 computers in the domain after a few days freeze when the trigger in the Task Scheduler to start wufuc when the computer is turned on is triggered. After disable this trigger - the wufuc started normally with the user's logon. Hanging in the wufuc logs are not fixed. If you have any debug build with detailed logging - i can test and reproduce problem.

**Comment by zeffy** [comment]
Ok I'm going to take a harder look at this and see if I can figure out what's happening.

> After disable this trigger - the wufuc started normally with the user's logon. Hanging in the wufuc logs are not fixed.

@kli3ma Could you elaborate? Turning off the system boot trigger allowed you to log in successfully, but wufuc still had issues after user login, am I understanding that correctly?

> If you have any debug build with detailed logging - i can test and reproduce problem.

In the event that writing to the log file fails (along with other general diagnostic messages), wufuc instead emits debug messages that you can see with [DebugView](https://docs.microsoft.com/en-us/sysinternals/downloads/debugview) (make sure you tick Capture -> Capture Global Win32). You can try this but I don't know how useful that would be given that when the problem happens you're stuck on a non-interactive screen.

Beyond that, any windows event viewer messages that could shed any light on what's causing the hang would be helpful.

**Comment by kli3ma** [comment]
> Could you elaborate? Turning off the system boot trigger allowed you to log in successfully, but wufuc still had issues after user login, am I understanding that correctly?

No, after turning off system boot trigger - system boot successfully, after user log in, wufuc started and injected (sure, wufuc trigger in task sheduler on user login enabled) . Window "Unsupported Hardware" still appears, but updates work.

I try change wuauserv type from "shared process" to "own process", enable both wufuc trigger in Task Sheduler and test. Then system boot successfully, user login, but wufuc work unstable. Example log:
```
03/29/18 08:23:13 [rundll32.exe:1324] wufuc_inject(96): [INFO] Successfully injected into process! (ProcessId=2984)
03/29/18 08:23:13 [svchost.exe:2984] cb_start(137): [INFO] Hooked LoadLibraryExW! (Module=KernelBase.dll, Address=00007FF9C4158D10)
03/29/18 08:23:13 [svchost.exe:2984] wufuc_hook(158): [INFO] Supported Windows Update Agent version: 7.9.9600.18838
03/29/18 08:23:13 [svchost.exe:2984] wufuc_hook(178): [INFO] Matched IsDeviceServiceable function! (Offset=1C4DEC, Address=00007FF9ACBF4DEC)
03/29/18 08:23:13 [svchost.exe:2984] wufuc_hook(184): [INFO] Hooked IsDeviceServiceable! (Address=00007FF9ACBF4DEC)
03/29/18 08:41:36 [rundll32.exe:1324] RUNDLL32_StartW(105): [WARNING] A process wufuc injected into has crashed 1 time! (ProcessId=2984)
03/29/18 08:46:14 [rundll32.exe:1324] wufuc_inject(96): [INFO] Successfully injected into process! (ProcessId=4424)
03/29/18 08:46:14 [svchost.exe:4424] cb_start(137): [INFO] Hooked LoadLibraryExW! (Module=KernelBase.dll, Address=00007FF9C4158D10)
03/29/18 08:46:14 [svchost.exe:4424] wufuc_hook(158): [INFO] Supported Windows Update Agent version: 7.9.9600.18838
03/29/18 08:46:14 [svchost.exe:4424] wufuc_hook(178): [INFO] Matched IsDeviceServiceable function! (Offset=1C4DEC, Address=00007FF9A1354DEC)
03/29/18 08:46:15 [svchost.exe:4424] wufuc_hook(184): [INFO] Hooked IsDeviceServiceable! (Address=00007FF9A1354DEC)
03/29/18 09:04:19 [rundll32.exe:1324] RUNDLL32_StartW(105): [WARNING] A process wufuc injected into has crashed 2 times! (ProcessId=4424)
03/29/18 09:15:36 [rundll32.exe:1324] wufuc_inject(96): [INFO] Successfully injected into process! (ProcessId=3328)
03/29/18 09:15:36 [svchost.exe:3328] cb_start(137): [INFO] Hooked LoadLibraryExW! (Module=KernelBase.dll, Address=00007FF9C4158D10)
03/29/18 09:15:36 [svchost.exe:3328] wufuc_hook(158): [INFO] Supported Windows Update Agent version: 7.9.9600.18838
03/29/18 09:15:36 [svchost.exe:3328] wufuc_hook(178): [INFO] Matched IsDeviceServiceable function! (Offset=1C4DEC, Address=00007FF9A00B4DEC)
03/29/18 09:15:36 [svchost.exe:3328] wufuc_hook(184): [INFO] Hooked IsDeviceServiceable! (Address=00007FF9A00B4DEC)
03/29/18 09:25:38 [rundll32.exe:1324] RUNDLL32_StartW(105): [WARNING] A process wufuc injected into has crashed 3 times! (ProcessId=3328)
03/29/18 09:25:38 [rundll32.exe:1324] RUNDLL32_StartW(108): [ERROR] Crash threshold has been reached, disabling wufuc until next reboot!
```

I think - maybe this issue related to domain networks? wuauserv start on service trigger "Start then a machine policy changes" (SC qtriggerinfo wuauserv). In eventlog i can see messages about services hang, all this services share one process with wuauserv (group netsvcs).

**Comment by kli3ma** [comment]
Label "windows 7" - incorrect. I have this issue on windows 8.1 machines. 

Maybe issue can be realated with boot/speed order - the problem manifested itself first on computers equipped with SSD. And always issue appear after a few days after installing OS - as far as I know, windows perfoms some boot optiomization. Can you change wufuc start mechanism (some delay after start or somthing like that) - i can test.

**Comment by zeffy** [comment]
> Label "windows 7" - incorrect. I have this issue on windows 8.1 machines.

Fixed. :smiley: 

> Can you change wufuc start mechanism (some delay after start or somthing like that) - i can test.

I can try, but that seems more like a hack to work around the issue than a fix. I'd like to know what is actually causing the system hang in the first place. Introducing a delay could end up making things more complicated because some of wufuc's features depend on it being active prior to Windows Update starting for the first time - so I'd like to avoid this as a permanent solution if possible.

That said - without more information about what is going wrong during the hangs (specific modules or services that are faulting), or more specific environment conditions (what was happening prior to the hang, if updates were pending etc..), then I'm not really sure how to go about fixing it since I still have not been able to reproduce it in a VM...

**Comment by kli3ma** [comment]
Maybe it helps. I attach event logs from Task Sheduler wufuc log and System EventLog from moment, when computer start till computer hang.
[eventlogs.zip](https://github.com/zeffy/wufuc/files/1874902/eventlogs.zip)

**Comment by zeffy** [comment]
That's helpful! Gives me a better idea of what's going on. Indeed, all the services that are crashing (or timing out) are in the netsvcs group. 

Maybe unrelated, but I noticed you have ESET running, which appeared to also crash, although it was about a minute after netsvcs started having problems, so I don't necessarily think it is the cause. Just trying to cross off potential causes/environment factors, can you (or anyone else this is happening to) confirm that this does happen on other PCs without ESET?

Thanks.

**Comment by kli3ma** [comment]
Yes, i think the reason for suspending the computer is that the services critical for the future work are suspended. All this services share one process with wuaserv and task sheduler service. As i said - if i move wuaserv to own process - boot always secceffully.
About ESET - yes, its good idea. Tomorrow i will remove Eset, enable wufuc and test boot many times.

**Comment by zeffy** [comment]
@kli3ma Thanks! Is there any chance you could post event logs like you did before but without ESET active, so that I can what difference there is between these two scenarios? wufuc does defintely seem to be the cause of this rather than ESET (although it may have been exasperating it). 

Perhaps injecting into svchost.exe too early is causing a deadlock of some kind in the process? That could explain the lack of recorded crashes in wufuc's log and also why the services are timing out instead of "ending unexpectedly" in your logs. Although it is hard to say at this point.

Additionally, could you get a Service Control Manager event log from a PC **without** wufuc installed, so that I can see what services are starting on a successful boot? I think you were right before, that this issue is localized to PCs that are connected to a domain, or perhaps related to using a local WSUS server.  Having this log to compare with my own event logs could possibly help me be able to reproduce this.

**Comment by cloudtuotuo** [comment]
@zeffy After we changed GPO settings, only few computers reported the login hang issue. We're not sure if this issue had gone, or our users rebooted into safe mode then rebooted again according to our suggestion.

Any new update will let you know...

**Comment by zeffy** [comment]
>I dont understand load order - tasksheduler, wich start wufuc, contained in same proccess, where wuauserv. Wuauserv start on service trigger "Start then a machine/user policy changes", wufuc start with tasksheduler before on after this service trigger fire?

Generally the order on a system with default settings is:

- PC powers on 
- Core device drivers start 
- Automatic start services (including Scheduler, which starts system boot tasks like wufuc) 
- Delay start services (including wuauserv)

In my observations wuauserv usually does not start until around 3-5 minutes after the PC is fully powered on and idle.

>What happen, if wufuc started after wuauserv or simultaneously, maybe we have some race condition?

Ideally wufuc should be started **before** wuauserv, so that it can either take control of the svchost.exe that loads wuaueng.dll and patch it in real time before it has a chance to run the CPU check and show the "unsupported hardware" popup (shared process), or wait for wuauserv to start and take it over as quickly as possible (own process).

>I sure, issue not related with Eset or other services at all.

I agree with you that there's definitely an issue with wufuc that is causing these hangs, and wasn't trying to say it was caused by other services or ESET. However, I still have not been able to replicate this specific issue on my system or any of my VMs, so it is very difficult for me to know how to go about fixing it. That's what the logs were for, I've been trying to find anything that could be a different environmental factor that is causing wufuc to break. That said, I haven't found anything in them that stands out yet, as you said there was nothing too interesting in the event logs.

I'll keep trying to figure this out though..

**Comment by zeffy** [comment]
>Look in console ''SC qtriggerinfo wuauserv".

Interesting, when I run that I get `service wuauserv has not registered for any start or stop triggers.`, my wuauserv is indeed set as "Auto start (delay)", so maybe that could have something to do with the difference?

>Then domain GPO is the necessary conditions for reproducing issue?

That's likely. I've been thinking that as well. I'll have to look into how to set one up so that I can delve further into this.

Thanks again for all your feedback and useful information!

**Comment by kli3ma** [comment]
> my wuauserv is indeed set as "Auto start (delay)"

It's strange. In the evening i check it on home machine (without any domains).  Let clarify configuration: i test wufuc in win8.1 with all updates at now.

>  I'll have to look into how to set one up so that I can delve further into this.

It is not worth it. Before you said "Ideally wufuc should be started before wuauserv", but what happen if wufuc start after or simultaneously with wuauserv? I think - this is what happen in my case.

> Thanks again for all your feedback and useful information!

Thank you for great work. New equipment with old licenses at work - I start to hate MS :)

**Comment by cloudtuotuo** [comment]
@zeffy Bad news. This morning, about 10 PC got the hang on issue...

**Comment by zeffy** [comment]
@cloudtuotuo I'm still working on solving this, but in the meanwhile you can try what @kli3ma suggested above and turn off the system startup trigger in the Task Scheduler for PCs that are affected by this issue, since that seems to bypass the problem.

I apologize for any inconvenience or headache this problem may have caused.

**Comment by cloudtuotuo** [comment]
@zeffy Thank you for what you did on this great patch. We'll always be your side.

**Comment by f-c-s** [comment]
Hello,

I have a similar problem. I installed wufuc on 27.04.2018 on the fresh installation of Windows 7 Pro x64 I7-7700 (Kaby lake) and I downloaded updates until reach "Unsupported hardware" message. 

I have installed Eset Internet Security 11.54. 

I'm preparing this computer to work from time to time (I use different produce machine). Yesterday I wanted to continue preparing new computer and it hanged on login screen as described above. I needed to make hard reset and run it in safe mode, I have logged successful, but after restarting this machine still stopped on welcome screen with message "Waiting ...".

The last version of this patch use Windows task scheduler. 
Is it possible to come back to run this patch manually ? 
I have turned off windows update. I decide when I want to install updates. Usually I make a backup of system disk before installing updates. I this case I can manually run patch if it will be necessary before updating windows.

Is it still possible ?

Regards
ML

**Comment by zeffy** [comment]
I'm currently in the process putting together a much less invasive version of wufuc that should hopefully resolve this. It will handle everything externally rather than injecting itself into `svchost.exe` and hooking various functions, which should make it a lot more stable (also a lot less code is needed. 

Doing it this way will re-introduce incompatibility with UpdatePack7R2, however (#100) which is why I have tried to avoid doing it this way until now, but as things stand I think it will better overall, and it will still be possible to work around the incompatibility manually for the people who are affected by it.

@f-c-s In regards to your specific question about patching the wuaueng.dll file, yes it is still possible, but I don't maintain scripts for it anymore. I explain how to do it manually here #117 if you are interested (basic knowledge of assembly language and debugging is recommended). 

Otherwise, your best option is to just wait until I get the next version done (I'm hoping for a release this week, assuming I don't have any big issues).

**Comment by kli3ma** [comment]
Sure, i will test it and report. Thank you!

**Comment by cloudtuotuo** [comment]
I've distributed this new patch to our PCs. I'll update you once I get something.

**Comment by CuoreSportivo** [comment]
I was about to deploy the patch in three machines that belong to a domain until I noticed the thread. I hope the fact that no one has yet reported back is positive... :)

**Comment by zeffy** [comment]
@kli3ma @cloudtuotuo It's been around a week, have either of you experienced any issues with the new version (besides the occasional "unsupported hardware" popup)? :crossed_fingers:

**Comment by kli3ma** [comment]
Wufuc was installed on 4 machines about a week ago. Everything works well. Except popup on every boot :)

**Comment by zeffy** [comment]
@kli3ma Excellent, I'm glad to hear it's working so far for you! Also, I'm currently working on the popup issue, you can follow my progress on it over at #158.

If I could get confirmation from one or two other people that the hangs indeed no longer occur, I think this issue could probably be closed.

**Comment by cloudtuotuo** [comment]
So far, everything's fine. Thanks @zeffy
