### ISSUE TITLE
Stopped working again

### ISSUE THREAD

**Issue by Moltresrider** [zeffy/wufuc#63]
using the patch that was produced a couple weeks ago on a Tuesday no longer works. Getting "Unsupported hardware" again on a Sandy Bridge CPU yet again. The patch keeps quit working. 0.6.1 is no longer working anymore

**Comment by zeffy** [comment]
I'd really like to help you, but without the information I asked for in your last issue #54 that you never replied to, there isn't much I can do. 

**Please read the [reporting an issue](https://github.com/zeffy/wufuc#reporting-an-issue-) section in the readme and reply back with the information requested or your issue will be closed again. Thank you.**

**Comment by Moltresrider** [comment]
There isn't Dbgview.exe in the wufuc zip so I cannot provide that.

But the output of the helper reports:

Copyright (C) 2017 zeffy
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; see COPYING.txt for details.

The Windows Update service is stopping.
The Windows Update service was stopped successfully.

The requested service has already been started.

More help is available by typing NET HELPMSG 2182.

INFO: Scheduled task "wufuc.{72EEE38B-9997-42BD-85D3-2DD96DA17307}" has already
been enabled.
SUCCESS: The parameters of scheduled task "wufuc.{72EEE38B-9997-42BD-85D3-2DD96D
A17307}" have been changed.
INFO: scheduled task "wufuc.{72EEE38B-9997-42BD-85D3-2DD96DA17307}" is currently
 running.
SUCCESS: Attempted to run the scheduled task "wufuc.{72EEE38B-9997-42BD-85D3-2DD
96DA17307}".
The Windows Update service is starting.
The Windows Update service was started successfully.

Restarted wufuc and wuauserv.

Press any key to continue . . .

**Comment by zeffy** [comment]
I can't redistribute Dbgview.exe with wufuc because it would be against the Sysinternals software license terms:

> You may not: ...
> * publish the software for others to copy; ...

There is a link to download it in the section of the readme that I linked you to before, but here it is again for your convenience: https://technet.microsoft.com/en-us/sysinternals/debugview.aspx

**Comment by zeffy** [comment]
Hey @Moltresrider, I made some changes to the logging system in the unstable builds. Now they write to log files, so **you don't have to use DebugView anymore**. Hopefully this should make everything easier.

All you have to do is uninstall the old version (if applicable) and install this one, and there will be two `.log` files sitting in the same directory as `wufuc64.dll`. Just post them here. :)

[Get the new x64 build here.](https://ci.appveyor.com/project/zeffy/wufuc/build/0.7.0.31/job/2p12m63a7c5g2tt8/artifacts)

Also, I made some changes to the installation process and it is entirely possible I fixed whatever was causing you issues, so could you please check whether these work correctly for you or not? Thanks.

**Comment by Tjazz38** [comment]
Hey, Zeffy. So far the program has worked great! I have not had any more of the stupid Microsoft popups. Thanks, again!

**Comment by Moltresrider** [comment]
I reapplied the patch and it is working again! But it still does not explain the seemingly random times that it stops working and why I am getting this on an older PC (still) when Microsoft supposedly fixed that problem. Sandy Bridge is not supposed to be on that list.

**Comment by zeffy** [comment]
@Tjazz38 Awesome!

@Moltresrider Yeah, I'm not really sure either. I adjusted the installer and the scheduled task so they should be slightly more reliable now, but please let me know if you keep having problems.

**Comment by zeffy** [comment]
@Tjazz38 Awesome!

@Moltresrider Yeah, I'm not really sure either. I adjusted the installer and the scheduled task so they should be slightly more reliable now, but please let me know if you keep having problems.

Regarding your Sandy Bridge CPU, could you tell me what model it is? I'd like to add it to the list of wrongfully blocked CPUs on the readme. It seems that old laptop models have been getting blocked quite frequently.

**Comment by Moltresrider** [comment]
Yeah, this is an Intel. The laptop model is Lenovo b570

**Comment by zeffy** [comment]
Well, according to the tech specs for the Lenovo B570 they came with several different kinds of CPUs depending on the tier you got. You can find your CPU model by going to the start menu and typing in "System Information", and it will be under Processor.

**Comment by Moltresrider** [comment]
The thing listed for processor is TL;DR and there is no way to just copy it to the clipboard

**Comment by zeffy** [comment]
You can select the processor row and press Ctrl+C to copy it. Sorry, should have mentioned that.

**Comment by Moltresrider** [comment]
Processor	Intel(R) Pentium(R) CPU B940 @ 2.00GHz, 2000 Mhz, 2 Core(s), 2 Logical Processor(s)

**Comment by zeffy** [comment]
Thanks! I'll add it to the list.
